//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ImplSound.h
//  @ Date : 9/27/2012
//  @ Author : 
//
//


#if !defined(_IMPLSOUND_H)
#define _IMPLSOUND_H

#include "ISound.h"

class ImplSound : public ISound
{
};

#endif  //_IMPLSOUND_H
