//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ISound.h
//  @ Date : 9/27/2012
//  @ Author : 
//
//


#if !defined(_ISOUND_H)
#define _ISOUND_H


class ISound
{
public:
	void play();
	void stop();
};

#endif  //_ISOUND_H
