//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ISound.cpp
//  @ Date : 9/27/2012
//  @ Author : 
//
//


#include "ISound.h"

void ISound::play()
{

}

void ISound::stop()
{

}

