//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SoundManager.cpp
//  @ Date : 9/27/2012
//  @ Author : 
//
//


#include "SoundManager.h"
#include "ISound.h"
#include "SoundManagerStatus.h"

bool SoundManager::init(string configurationFile)
{

}

string SoundManager::getError()
{

}

ISound SoundManager::getSound(string soundName)
{

}

SoundManagerStatus SoundManager::getStatus()
{

}

