//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SoundManagerStatus.h
//  @ Date : 9/27/2012
//  @ Author : 
//
//


#if !defined(_SOUNDMANAGERSTATUS_H)
#define _SOUNDMANAGERSTATUS_H


enum SoundManagerStatus
{
	OK,
	CANT_OPEN_CONFIG_FILE,
	CANT_FIND_SOUND
};

#endif  //_SOUNDMANAGERSTATUS_H
